#!/bin/bash

# apply the loki multi tenant setup
kubectl apply -f .

# install Grafana helmchart
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm install grafana --namespace=co-monitoring grafana/grafana
# grafana password
kubectl get secret --namespace co-monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo

# expose grafana to localhost run in seperate terminal
kubectl port-forward svc/grafana -n co-monitoring 3000:80

# datasource url
http://loki-multi-tenant-proxy.co-monitoring.svc.cluster.local:3100

# team-alpha-dev namespace (pre configured as example)
# beta credentials are generated by credsync service
username: team-alpha-dev
password: alpha


